name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu bc bison flex libssl-dev make

    - name: Clone Kernel Source
      run: |
        git clone --depth=1 https://github.com/xiaomi-sdm660/android_kernel_xiaomi_sdm660.git kernel
        cd kernel
        git checkout 11-EAS

    - name: Build Kernel
      run: |
        cd kernel
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- sdm660_defconfig
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: kernel/arch/arm64/boot/Image.gz-dtb
